apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-node
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
      - name: hellonode
        image: eu.gcr.io/sd-test-jenkins-cd/kbnw-express-app:latest
        ports:
        - containerPort: 3000
