image: pindar/gcloud-kubectl-docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - echo "$GCLOUD_GITLAB_CI_SERVICE_ACCOUNT_KEY" | base64 -d > gcloud.p12
  - gcloud auth activate-service-account "$GCLOUD_GITLAB_CI_SERVICE_ACCOUNT" --key-file=gcloud.p12  --project "$GCLOUD_PROJECT" --quiet
  - export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcloud.p12
  - gcloud --quiet container clusters get-credentials $CLUSTER_NAME --zone $GCLOUD_ZONE

after_script:
  # clean up
  - rm -rf *

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:${CI_BUILD_TAG:-`echo $CI_BUILD_REF | head -c 8`}" .
    - gcloud docker -- push "$CI_REGISTRY_IMAGE:${CI_BUILD_TAG:-`echo $CI_BUILD_REF | head -c 8`}"

deploy_branch:
  stage: deploy
  script:
    # Don't use public load balancing for development branches
    - sed -i.bak 's#LoadBalancer#ClusterIP#' ./k8s/services/frontend.yaml
    - chmod +x k8s/deploy.sh
    - ./k8s/deploy.sh ${CI_BUILD_REF_SLUG}
    - echo 'To access your environment run `kubectl proxy`'
    - echo "Then access your service via http://localhost:8001/api/v1/proxy/namespaces/${CI_BUILD_REF_SLUG}/services/hello-deployment-frontend:80/"
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: http://localhost:8001/api/v1/proxy/namespaces/$CI_BUILD_REF_SLUG/services/hello-deployment-frontend:80/
    on_stop: stop_review
  only:
    - branches
  except:
    - master

stop_review:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Remove review app"
    - kubectl delete namespaces ${CI_BUILD_REF_SLUG}
  when: manual
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  only:
    - triggers

deploy_staging:
  variables:
    DOMAIN: ""
    NAMESPACE: "staging"
  stage: deploy
  script:
    - chmod +x k8s/deploy.sh
    - ./k8s/deploy.sh $NAMESPACE
    - export DOMAIN=`kubectl --namespace=$NAMESPACE get service/hello-deployment-frontend --output=json | jq -r '.status.loadBalancer.ingress[0].ip'`
    - echo "Then access your service via http://$DOMAIN"
  environment:
    name: $NAMESPACE
    url: http://$DOMAIN
  only:
    - master
    - tags

deploy_production:
  variables:
    DOMAIN: ""
    NAMESPACE: "production"
  stage: deploy
  script:
    - chmod +x k8s/deploy.sh
    - ./k8s/deploy.sh $NAMESPACE
    - export DOMAIN=`kubectl --namespace=$NAMESPACE get service/hello-deployment-frontend --output=json | jq -r '.status.loadBalancer.ingress[0].ip'`
    - echo "Then access your service via http://$DOMAIN"
  environment:
    name: $NAMESPACE
    url: http://$DOMAIN
  when: manual
  only:
    - tags
