apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
  - host: STAGING_DOMAIN
    http:
      paths:
      - backend:
          serviceName: hello-deployment-frontend-staging
          servicePort: 3000
  - host: PRODUCTION_DOMAIN
    http:
      paths:
      - backend:
          serviceName: hello-deployment-frontend-production
          servicePort: 3000
