apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-deployment-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-node
      env: staging
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: hello-node
        env: staging
    spec:
      containers:
      - name: hellonode
        image: IMAGE_PLACEHOLDER
        imagePullPolicy: IfNotPresent
        ports:
        - name: app-port
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: app-port
          initialDelaySeconds: 3
          periodSeconds: 3
        # The readiness probe must be exposed on the port matching the servicePort specified in the Ingress
        # https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce/examples/health_checks
        readinessProbe:
          httpGet:
            path: /healthz
            port: app-port
          initialDelaySeconds: 5
          periodSeconds: 5
