apiVersion: v1
kind: Service
metadata:
  name: hello-deployment-frontend-staging
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: hello-node
    env: staging
