apiVersion: v1
kind: Service
metadata:
  name: hello-deployment-frontend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: hello-node
